version: '3.4'

services:
  andnet.manager.server:
    image: ${DOCKER_REGISTRY-}andnet-manager-server
    container_name: AndNet.Manager.Server
    restart: "no"
    ports:
      - "5080:80"
    build:
      context: .
      dockerfile: src/Server/Dockerfile

  andnet.manager.database:
    image: ${DOCKER_REGISTRY-}andnet-manager-database
    container_name: AndNet.Manager.Database
    restart: "no"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"
    build:
      context: .
      dockerfile: postgres.DOCKERFILE